# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='vari',
            name='type1',
            field=models.CharField(default='one', max_length=100),
        ),
    ]
