# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160724_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 30, 15, 4, 20, 43206)),
        ),
    ]
