# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160730_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='image',
            field=models.ImageField(default='media/rainbow.jpg', upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 30, 18, 57, 15, 693195)),
        ),
    ]
